In [44]:
import pandas as pd
import numpy as np
import os
from datetime import datetime

In [51]:
df = pd.read_csv(os.path.join("dataset", "GrupoFleuryAgosto", "GrupoFleury_Exames_2.csv"), sep="|")
df.head()

,ID_PACIENTE,DT_COLETA,DE_ORIGEM,DE_EXAME,DE_ANALITO,DE_RESULTADO,CD_UNIDADE,DE_VALOR_REFERENCIA
0,1AD07C7A1E4D80B608DD7A650766CCF0,19/03/2020,LAB,"NOVO CORONAVÍRUS 2019 (SARS-CoV-2), DETECÇÃO P...","Covid 19, Detecção por PCR",NÃO DETECTADO,NaN,Não detectado
1,1AD07C7A1E4D80B608DD7A650766CCF0,19/03/2020,LAB,"NOVO CORONAVÍRUS 2019 (SARS-CoV-2), DETECÇÃO P...","Covid 19, Material",raspado de nasofaringe,NaN,NaN
2,7B10786D64F27D7732503D915A38DE6F,30/12/2019,LAB,"HEMOGRAMA, sangue total",Hemoglobina,"15,2",g/dL,"13,5 a 17,5"
3,7B10786D64F27D7732503D915A38DE6F,30/12/2019,LAB,"HEMOGRAMA, sangue total",VCM,"89,2",fL,"81,0 a 95,0"
4,7B10786D64F27D7732503D915A38DE6F,30/12/2019,LAB,"HEMOGRAMA, sangue total",Leucócitos,5940,/mm3,3.500 a 10.500

In [52]:
df.DE_RESULTADO.value_counts()

NÃO REAGENTE                                                                                                          369595
0,1                                                                                                                   180863
negativa                                                                                                              108512
não reagente                                                                                                          101166
0,6                                                                                                                    80178
                                                                                                                       ...
microcitose moderada, poiquilocitose moderada, algumas hemácias em alvo, raros esquizócitos, policromasia discreta         1
78330                                                                                                                      1
587,2                                                                                                                      1
1037000                                                                                                                    1
15:27                                                                                                                      1
Name: DE_RESULTADO, Length: 20811, dtype: int64

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5873403 entries, 0 to 5873402
Data columns (total 8 columns):
 #   Column               Dtype
---  ------               -----
 0   ID_PACIENTE          object
 1   DT_COLETA            object
 2   DE_ORIGEM            object
 3   DE_EXAME             object
 4   DE_ANALITO           object
 5   DE_RESULTADO         object
 6   CD_UNIDADE           object
 7   DE_VALOR_REFERENCIA  object
dtypes: object(8)
memory usage: 358.5+ MB

In [54]:
df = df[df.DE_RESULTADO.str.isnumeric()]
df.DE_RESULTADO = df.DE_RESULTADO.apply(np.float32)
df.DT_COLETA = df.DT_COLETA.apply(lambda date: datetime(int(date[6:]), int(date[3:5]), int(date[0:2])))

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1819445 entries, 4 to 5873398
Data columns (total 8 columns):
 #   Column               Dtype
---  ------               -----
 0   ID_PACIENTE          object
 1   DT_COLETA            datetime64[ns]
 2   DE_ORIGEM            object
 3   DE_EXAME             object
 4   DE_ANALITO           object
 5   DE_RESULTADO         float64
 6   CD_UNIDADE           object
 7   DE_VALOR_REFERENCIA  object
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 124.9+ MB

In [57]:
df.groupby("ID_PACIENTE").count()

,DT_COLETA,DE_ORIGEM,DE_EXAME,DE_ANALITO,DE_RESULTADO,CD_UNIDADE,DE_VALOR_REFERENCIA
ID_PACIENTE,,,,,,,
00007BB4274722A63A38D415ACCD7705,74,74,74,74,74,74,64
000085C48A31F50AE4F147392F6F35CF,93,93,93,93,93,93,84
00029A8E0091126C7A0D22568D37C5AA,14,14,14,14,14,10,11
0005E27C2FE72D781FC713004443FEA3,56,56,56,56,56,52,53
0005F41F61454BBE455B910CE6CF30F6,35,35,35,35,35,28,26
...,...,...,...,...,...,...,...
FFF9C583FA951A957A64236C005ED074,25,25,25,25,25,25,24
FFFB34F871D6727F0B9CEBF5F00F8314,16,16,16,16,16,16,16
FFFCBF9E5F54A15C71B56129A4E65774,100,100,100,100,100,100,88
FFFD9CB0DA1DEFECCCEFBA68D04E940D,30,30,30,30,30,29,29
FFFDEB16C0665899C5F4E41C117BCFEA,50,50,50,50,50,47,47